### ISSUE TITLE
[QUESTION] - Migration of parachain to paseo after rococo is halted

### ISSUE THREAD

**Issue by Mrigesh901** [paseo-network/support#104]
### Question Overview

I’m reaching out with some queries regarding our parachain migration from Rococo to Paseo, especially given that Rococo has now halted and is no longer producing blocks.

### Detailed Description

Our parachain has been halted for some time, and we currently don’t have a pallet implemented to disable the lastRelayChainBlockNumber check. As a result, we’ve encountered some challenges in migrating the parachain state to Paseo.
 
Is there any possible way to migrate the parachain’s state and history now that Rococo has stopped producing blocks?
As we understand, normally a runtime upgrade or killStorage approach would require block production to include the changes. However, given that the relay chain has halted, we’re unable to execute such calls.

### Expected Outcome

Our goal is to ensure a smooth migration of state and history of parachain, and we’re keen to explore any options that may still be available despite Rococo's halt. Any advice or insights you could share would be immensely appreciated.

 Thank you for your time and support.

**Comment by al3mart** [comment]
In order to migrate your history you can't modify the genesis in the spec.
Given that there might not be a way for you to mutate the storage keys that could make the transition easier the only thing that comes to mind is exploring the option of leveraging [`codeSubstitutes`](https://github.com/paritytech/polkadot-sdk/blob/7240b474b92028a1645de6fdb9e0a8aa28dc86be/substrate/client/chain-spec/src/lib.rs#L426).
Where you guys use a new wasm that won't check for the relay blocks increments.

There are some old comments about that property here - https://substrate.stackexchange.com/questions/5828/what-is-codesubstitutes-in-the-chain-spec

**Comment by Mrigesh901** [comment]
@al3mart  So basically we need to generate a wasm ( no code change ) , add the codesubstitute field in raw chainspec with last block no. along with changes to paraid, protocolid etc. and submit the ticket to onboard the chain to paseo?

**Comment by Mrigesh901** [comment]
@al3mart , how much work is there to do if we use the codesubstitutes method ? Do we need to just make changes in chainspec or do we need to make any changes in runtime code?

**Comment by hbulgarini** [comment]
closing this as the parachain is up and running.
