### ISSUE TITLE
[Parachain Onboarding | Slot Request] WeTEE: 4545

### ISSUE THREAD

**Issue by BurnWW** [paseo-network/support#111]
### Parachain Name

WeTEE

### ParaID

4545

### Parachain Manager Account

5DtWKe2tC7FNzhMQZrdgKyDiSWJ9dwLraJVcx1mrHxyorDTW

### Upload your Genesis State - Do not submit a compressed file.

0x000000000000000000000000000000000000000000000000000000000000000000121f9f5e2f29ae72f8c153f426ff68d0c21972a89f243c052b4905d32ad295c603170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[genesis-wasm.txt](https://github.com/user-attachments/files/17775633/genesis-wasm.txt)

**Comment by al3mart** [comment]
Your chain is now being onboarded

![image](https://github.com/user-attachments/assets/83cc4656-aee9-44d4-b686-65128057d175)


Please, feel free to follow up using on demand coretime or bulk. - https://wiki.polkadot.network/docs/learn-guides-coretime-parachains
In case you need some extra funds to procude coretime, feel free to drop us a message here.
Sorry for the late reply.

**Comment by hbulgarini** [comment]
hey @BurnWW, i apologize as well for the delay in delivering this onboarding. The reason for the delay is because for the last two weeks we were working with the coretime developer functionalities different ways to manipulate cores assigned from the broker as the pallet does not contain any public interface to manipulate cores manually as per demand. 

I have also transferred you 12K PAS that would be sufficient to buy a core for one month. If this needs to be renewed please let us know or use any of the two on demand cores available.

**Comment by BurnWW** [comment]
Thank you very much, we will immediately follow up on the procurement and launch of coretime.

**Comment by hbulgarini** [comment]
> Thank you very much, we will immediately follow up on the procurement and launch of coretime.

Yw! if you find any blocker please don't hesitate to contact us in Matrix in the support group channel:

https://matrix.to/#/#paseo-testnet-support:parity.io
